import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "@/src/app/_shared/styles/globals.css";
import Navbar from "@/src/app/_shared/components/layout/Navbar/Navbar";
import Footer from "@/src/app/_shared/components/layout/Footer/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "AILab",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${poppins.className} h-full antialiased`}>
      <body className="min-h-full flex flex-col bg-black">
        <Navbar />
        <div className="flex-1 pt-16">{children}</div>
        <Footer />
      </body>
    </html>
  );
}
